<div class="gist-meta">

    <span style="float: right; color: #369;">
         <a href="{{raw_url}}">view raw</a>
    </span>

    <span style="float: right; margin-right: 8px;">
         <a style="color: rgb(102, 102, 102);"
            href="{{blob_url}}">{{filename}}</a>
      </span>
    <!-- Generated by: https://github.com/trasweb/gist-it-php -->
</div>