<div class="gist-meta">

    <span class="raw-link">
         <a href="{{rawUrl}}">view raw</a>
    </span>

    <span class="blob-link">
         <a href="{{blobUrl}}">{{filename}}</a>
    </span>
    <!-- Generated by: https://github.com/trasweb/gist-it-php -->
</div>